config/routes.rb
Neptuno::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :companies

  resources :franchises

  resources :customers

  resources :administrations

  resources :consortia

  resources :functional_units

  resources :owners

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to(@customer, :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(@customer, :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= semantic_form_for @customer do |f|
  = f.semantic_errors

  = render('shared/common_form_buttons')

  = f.inputs do
    = f.input :name
    = f.input :address
    = f.input :cuit

app/views/customers/edit.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item t('scaffold.actions.back', :item => Customer.model_name.human).titlecase, customers_path
    - breadcrumb.item "#{@customer.name.titlecase}", customer_path(@customer), :active => true

- content_for(:controls) do
  = controls do |control|
    - control.item t('scaffold.actions.show').titlecase, @customer, :icon => 'application_get'

= render 'form'

app/views/customers/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Customer.model_name.human, customers_path

.clear
- if can?(:create, Customer)
  - content_for(:controls) do
    = controls do |control|
      - control.item t('scaffold.actions.new', :item => Customer.model_name.human).titlecase, new_customer_path, :icon => 'add'
      - control.item t('scaffold.actions.export').titlecase, customers_path( :format => 'pdf'), :icon => 'report_go'

.block
  - if @customers.any?
  %table.table
    %tr
      %th= Customer.human_attribute_name('name')
      %th= Customer.human_attribute_name('address')
      %th= Customer.human_attribute_name('cuit')
      %th.last

    - @customers.each do |customer|
      %tr
        %td= customer.name
        %td= customer.address
        %td= customer.cuit
        %td.last.actions
          = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), customer
          = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_customer_path(customer)
          = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), customer, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete
    .clear
    .block{:style => 'margin:20px;'}= paginate(@customers)
    .clear
.clear

app/views/customers/new.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item t('scaffold.actions.back').titlecase, customers_path
    - breadcrumb.item t('scaffold.actions.new', :item => Customer.model_name.human).titlecase , customers_path, :active => true

= render 'form'

app/views/customers/show.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item t('scaffold.actions.back', :item => Customer.model_name.human).titlecase, customers_path
    - breadcrumb.item "#{@customer.name.titlecase}", customer_path(@customer), :active => true

- content_for(:controls) do
  = controls do |control|
    - control.item t('scaffold.actions.edit').titlecase, edit_customer_path(@customer), :icon => 'application_edit'

= semantic_attributes_for(@customer) do |s|
  = s.attributes() do
    = s.attribute :name
    = s.attribute :address
    = s.attribute :cuit

.clear