config/routes.rb
Neptuno::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :companies

  resources :franchises

  resources :customers

  resources :administrations

  resources :consortia

  resources :functional_units

  resources :owners

end

app/models/functional_unit.rb
class FunctionalUnit < ActiveRecord::Base
  belongs_to :owner, :class_name => "Owner", :foreign_key => "owner_id"
  belongs_to :consortium, :class_name => "Consortium", :foreign_key => "consortium_id"
end

app/controllers/functional_units_controller.rb
class FunctionalUnitsController < ApplicationController
  # GET /functional_units
  # GET /functional_units.xml
  def index
    @functional_units = FunctionalUnit.order(:owner_id).page(params[ :page ]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @functional_units }
    end
  end

  # GET /functional_units/1
  # GET /functional_units/1.xml
  def show
    @functional_unit = FunctionalUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @functional_unit }
    end
  end

  # GET /functional_units/new
  # GET /functional_units/new.xml
  def new
    @functional_unit = FunctionalUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @functional_unit }
    end
  end

  # GET /functional_units/1/edit
  def edit
    @functional_unit = FunctionalUnit.find(params[:id])
  end

  # POST /functional_units
  # POST /functional_units.xml
  def create
    @functional_unit = FunctionalUnit.new(params[:functional_unit])

    respond_to do |format|
      if @functional_unit.save
        format.html { redirect_to(@functional_unit, :notice => 'Functional unit was successfully created.') }
        format.xml  { render :xml => @functional_unit, :status => :created, :location => @functional_unit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @functional_unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /functional_units/1
  # PUT /functional_units/1.xml
  def update
    @functional_unit = FunctionalUnit.find(params[:id])

    respond_to do |format|
      if @functional_unit.update_attributes(params[:functional_unit])
        format.html { redirect_to(@functional_unit, :notice => 'Functional unit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @functional_unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /functional_units/1
  # DELETE /functional_units/1.xml
  def destroy
    @functional_unit = FunctionalUnit.find(params[:id])
    @functional_unit.destroy

    respond_to do |format|
      format.html { redirect_to(functional_units_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/functional_units_helper.rb
module FunctionalUnitsHelper
end

app/views/functional_units/_form.html.haml
= semantic_form_for @functional_unit do |f|
  = f.semantic_errors

  .field
    = f.label :owner
    = f.input :owner_id, :label => true, :as => :select, :collection => Owner.all.map{|c| [c.last_name, c.id]}, :include_blank => false
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :consortium
    = f.input :consortium_id, :label => true, :as => :select, :collection => Consortium.all.map{|c| [c.name, c.id]}, :include_blank => false
  .actions
    = f.submit 'Save'

app/views/functional_units/edit.html.haml
%h1 Editing functional_unit

= render 'form'

= link_to 'Show', @functional_unit
\|
= link_to 'Back', functional_units_path

app/views/functional_units/index.html.haml
%h1 Listing functional_units

= paginate(@functional_units)
%br
%br
%table.tableStandard
  %tr
    %th Owner
    %th Location
    %th Consortium
    %th{ :colspan => '3', :style => "text-align:center;"} Actions
  - @functional_units.each do |functional_unit|
    %tr
      %td= functional_unit.owner.last_name + ', ' + functional_unit.owner.last_name
      %td= functional_unit.location
      %td= functional_unit.consortium.try('name')
      %td= link_to 'Show', functional_unit
      %td= link_to 'Edit', edit_functional_unit_path(functional_unit)
      %td= link_to 'Destroy', functional_unit, :confirm => 'Are you sure?', :method => :delete

%br
= paginate(@functional_units)
%br
%br
= link_to 'New Functional unit', new_functional_unit_path

app/views/functional_units/new.html.haml
%h1 New functional_unit

= render 'form'

= link_to 'Back', functional_units_path

app/views/functional_units/show.html.haml
%h1 Show functional units
%p#notice= notice

%p
  %b Owner:
  = @functional_unit.owner.last_name + ', ' + @functional_unit.owner.first_name
%p
  %b Location:
  = @functional_unit.location
%p
  %b Consortium:
  = link_to @functional_unit.consortium.name, consortium_path(@functional_unit.consortium)

= link_to 'Edit', edit_functional_unit_path(@functional_unit)
\|
= link_to 'Back', functional_units_path