config/routes.rb
Neptuno::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :companies

  resources :franchises

  resources :customers

  resources :administrations

  resources :consortia

  resources :functional_units

  resources :owners

end

app/controllers/franchises_controller.rb
class FranchisesController < ApplicationController
  # GET /franchises
  # GET /franchises.xml
  def index
    @franchises = Franchise.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @franchises }
    end
  end

  # GET /franchises/1
  # GET /franchises/1.xml
  def show
    @franchise = Franchise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @franchise }
    end
  end

  # GET /franchises/new
  # GET /franchises/new.xml
  def new
    @franchise = Franchise.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @franchise }
    end
  end

  # GET /franchises/1/edit
  def edit
    @franchise = Franchise.find(params[:id])
  end

  # POST /franchises
  # POST /franchises.xml
  def create
    @franchise = Franchise.new(params[:franchise])

    respond_to do |format|
      if @franchise.save
        format.html { redirect_to(@franchise, :notice => 'Franchise was successfully created.') }
        format.xml  { render :xml => @franchise, :status => :created, :location => @franchise }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @franchise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /franchises/1
  # PUT /franchises/1.xml
  def update
    @franchise = Franchise.find(params[:id])

    respond_to do |format|
      if @franchise.update_attributes(params[:franchise])
        format.html { redirect_to(@franchise, :notice => 'Franchise was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @franchise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /franchises/1
  # DELETE /franchises/1.xml
  def destroy
    @franchise = Franchise.find(params[:id])
    @franchise.destroy

    respond_to do |format|
      format.html { redirect_to(franchises_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/views/franchises/_form.html.haml
= semantic_form_for @franchise do |f|
  = f.semantic_errors

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :company
    = f.input :company_id, :label => true, :as => :select, :collection => Company.all.map{|c| [c.name, c.id]}, :include_blank => false

  .actions
    = f.submit 'Save'

app/views/franchises/edit.html.haml
%h1 Editing franchise

= render 'form'

= link_to 'Show', @franchise
\|
= link_to 'Back', franchises_path

app/views/franchises/index.html.haml
%h1 Listing franchises

%table.tableStandard
  %tr
    %th Name
    %th Company
    %th{ :colspan => '3', :style => "text-align:center;"} Actions
  - @franchises.each do |franchise|
    %tr
      %td= franchise.name
      %td= franchise.company.try('name')
      %td= link_to 'Show', franchise
      %td= link_to 'Edit', edit_franchise_path(franchise)
      %td= link_to 'Destroy', franchise, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Franchise', new_franchise_path

app/views/franchises/new.html.haml
%h1 New franchise

= render 'form'

= link_to 'Back', franchises_path

app/views/franchises/show.html.haml
%h1 Show Franchise
%p#notice= notice

%p
  %b Name:
  = @franchise.name
%p
  %b Company:
  = link_to @franchise.company.name, company_path(@franchise.company)
%p
  %b Administrations
%table.tableStandard
  %tr
    %th name
    %th
  - @franchise.administrations.each do |administration|
    %tr
      %td= administration.name
      %td= link_to 'ver', administration_path(administration)

= link_to 'Edit', edit_franchise_path(@franchise)
\|
= link_to 'Back', franchises_path